Metrics/LineLength:
  Max: 120
Style/AndOr:
  EnforcedStyle: conditionals
Style/Documentation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
